In [1]:
import tensorflow as tf

In [2]:
a = tf.reshape(tf.range(4), [2, 2])

In [3]:
a

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

# pad操作

In [4]:
tf.pad(a, [[2, 1], [1, 0]])

<tf.Tensor: id=7, shape=(5, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 2, 3],
       [0, 0, 0]], dtype=int32)>

In [5]:
tf.pad(a, [[1,2], [1,2]])

<tf.Tensor: id=9, shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 2, 3, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [24]:
tf.pad(a,[[1, 1], [1, 1]], mode='REFLECT')

<tf.Tensor: id=36, shape=(4, 4), dtype=int32, numpy=
array([[3, 2, 3, 2],
       [1, 0, 1, 0],
       [3, 2, 3, 2],
       [1, 0, 1, 0]], dtype=int32)>

In [26]:
tf.pad(a,[[2, 1], [1, 1]], mode='SYMMETRIC')

<tf.Tensor: id=40, shape=(5, 4), dtype=int32, numpy=
array([[2, 2, 3, 3],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [2, 2, 3, 3],
       [2, 2, 3, 3]], dtype=int32)>

# tile操作

In [6]:
b = tf.reshape(tf.constant([1, 2, 3, 4]), [2, 2])

In [8]:
tf.tile(b, [2, 1])

<tf.Tensor: id=14, shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]], dtype=int32)>

In [9]:
tf.tile(b, [1, 2])

<tf.Tensor: id=16, shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 1, 2],
       [3, 4, 3, 4]], dtype=int32)>

In [10]:
bb = tf.expand_dims(b, axis=0)

In [11]:
tf.tile(bb, [2, 1, 1])

<tf.Tensor: id=20, shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)>

# broadcast_to操作

In [12]:
tf.broadcast_to(bb, [2, 1, 1])

InvalidArgumentError: Unable to broadcast tensor of shape [1,2,2] to tensor of shape [2,1,1] [Op:BroadcastTo]

In [13]:
bb

<tf.Tensor: id=18, shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [14]:
c = tf.reshape(tf.constant([1, 2, 3, 4]), [2, 2])

In [15]:
cc = tf.expand_dims(c, axis=0)

In [17]:
tf.broadcast_to(cc, [2,2,2])

<tf.Tensor: id=29, shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]], dtype=int32)>