In [1]:
import tensorflow as tf

In [2]:
a = tf.random.shuffle(tf.range(8))
b= tf.random.uniform([3,3], maxval=10, dtype=tf.int32)

In [3]:
a, b

(<tf.Tensor: id=4, shape=(8,), dtype=int32, numpy=array([3, 7, 0, 6, 5, 1, 4, 2], dtype=int32)>,
 <tf.Tensor: id=8, shape=(3, 3), dtype=int32, numpy=
 array([[0, 6, 6],
        [5, 6, 1],
        [8, 7, 3]], dtype=int32)>)

# sort操作

In [4]:
tf.sort(a) # 默认升序 direction='ASCENDING'

<tf.Tensor: id=19, shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [5]:
tf.sort(a, direction='DESCENDING') #降序

<tf.Tensor: id=27, shape=(8,), dtype=int32, numpy=array([7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [6]:
tf.sort(a, direction='ASCENDING') #升序

<tf.Tensor: id=39, shape=(8,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int32)>

In [7]:
tf.sort(b)

<tf.Tensor: id=50, shape=(3, 3), dtype=int32, numpy=
array([[0, 6, 6],
       [1, 5, 6],
       [3, 7, 8]], dtype=int32)>

In [8]:
tf.sort(b, axis=1) # 默认按照axis=1升序

<tf.Tensor: id=61, shape=(3, 3), dtype=int32, numpy=
array([[0, 6, 6],
       [1, 5, 6],
       [3, 7, 8]], dtype=int32)>

In [9]:
tf.sort(b, axis=0, direction='DESCENDING')

<tf.Tensor: id=73, shape=(3, 3), dtype=int32, numpy=
array([[8, 7, 6],
       [5, 6, 3],
       [0, 6, 1]], dtype=int32)>

# argsort操作

In [10]:
idx = tf.argsort(a, direction='DESCENDING') # 降序排列对应的索引

In [11]:
idx

<tf.Tensor: id=82, shape=(8,), dtype=int32, numpy=array([1, 3, 4, 6, 0, 7, 5, 2], dtype=int32)>

In [12]:
tf.gather(a, idx)

<tf.Tensor: id=84, shape=(8,), dtype=int32, numpy=array([7, 6, 5, 4, 3, 2, 1, 0], dtype=int32)>

In [13]:
tf.argsort(a) # 默认升序排列对应的索引

<tf.Tensor: id=94, shape=(8,), dtype=int32, numpy=array([2, 5, 7, 0, 6, 4, 3, 1], dtype=int32)>

In [14]:
tf.argsort(b) # 默认按照axis=1升序排列

<tf.Tensor: id=104, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int32)>

In [17]:
tf.argsort(b, axis=1) 

<tf.Tensor: id=125, shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [2, 0, 1],
       [2, 1, 0]], dtype=int32)>

In [18]:
tf.argsort(b, axis=0, direction='DESCENDING')

<tf.Tensor: id=137, shape=(3, 3), dtype=int32, numpy=
array([[2, 2, 0],
       [1, 0, 2],
       [0, 1, 1]], dtype=int32)>

# top_k操作

In [20]:
b

<tf.Tensor: id=8, shape=(3, 3), dtype=int32, numpy=
array([[0, 6, 6],
       [5, 6, 1],
       [8, 7, 3]], dtype=int32)>

In [21]:
tf.math.top_k(b, 2) # 返回元组(values, indices)

TopKV2(values=<tf.Tensor: id=139, shape=(3, 2), dtype=int32, numpy=
array([[6, 6],
       [6, 5],
       [8, 7]], dtype=int32)>, indices=<tf.Tensor: id=140, shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 0],
       [0, 1]], dtype=int32)>)

In [22]:
res = tf.math.top_k(b, 2)

In [23]:
res.indices

<tf.Tensor: id=143, shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 0],
       [0, 1]], dtype=int32)>