In [1]:
import tensorflow as tf
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub

In [2]:
np.set_printoptions(precision=4)

In [3]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])

In [4]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [5]:
for elem in dataset:
    print(elem)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [6]:
it = iter(dataset)
next(it)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [7]:
next(it).numpy()

3

In [8]:
dataset.reduce(0, lambda state, value: state + value)

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [9]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))

In [10]:
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [11]:
dataset1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [12]:
for elem in dataset1:
    print(elem)

tf.Tensor([0.7057 0.1882 0.141  0.9582 0.0514 0.1404 0.8754 0.887  0.2139 0.3947], shape=(10,), dtype=float32)
tf.Tensor([0.0528 0.1005 0.0725 0.731  0.9113 0.7208 0.2308 0.6111 0.6227 0.0524], shape=(10,), dtype=float32)
tf.Tensor([0.4928 0.6245 0.9005 0.0323 0.8794 0.4204 0.2469 0.8489 0.9129 0.2528], shape=(10,), dtype=float32)
tf.Tensor([0.3411 0.7001 0.8936 0.562  0.5044 0.8158 0.8537 0.2782 0.1196 0.878 ], shape=(10,), dtype=float32)


In [13]:
dataset2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4]),
                                             tf.random.uniform([4, 10], maxval=100, dtype=tf.int32)))

In [14]:
dataset2

<TensorSliceDataset shapes: ((), (10,)), types: (tf.float32, tf.int32)>

In [15]:
for elem in dataset2:
    print(elem)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.5611422>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([26, 81, 63, 86, 68, 43, 99, 32, 77,  8], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.018838644>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([53, 29, 47, 85, 87, 76, 94, 26, 71, 71], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.66992235>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([29, 58, 49, 53,  7, 75,  5, 36,  1, 83], dtype=int32)>)
(<tf.Tensor: shape=(), dtype=float32, numpy=0.09955895>, <tf.Tensor: shape=(10,), dtype=int32, numpy=array([54,  7, 85, 32, 12, 50, 94, 18, 43, 44], dtype=int32)>)


In [16]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(10,), dtype=tf.int32, name=None))

In [17]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

In [18]:
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(10,), dtype=tf.int32, name=None)))

In [19]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0,0],[1,2]], values=[1, 2],
                                                       dense_shape=[3, 4]))

In [20]:
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [21]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [22]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))
dataset1

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [23]:
for z in dataset1:
    print(z.numpy())

[2 1 4 9 2 7 4 1 8 3]
[2 3 6 2 6 7 8 3 4 8]
[1 1 6 5 8 2 4 6 8 6]
[7 5 7 8 8 2 4 2 7 8]


In [24]:
dataset2 = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))
dataset2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [25]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3

<ZipDataset shapes: ((10,), ((), (100,))), types: (tf.int32, (tf.float32, tf.int32))>

In [26]:
for a, (b, c) in dataset3:
    print('shapes: {a.shape}, {b.shape}, {c.shape}'.format(a=a, b=b, c=c))

shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
