In [1]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.0.0


# 数据限幅 clip_by_value 操作

In [3]:
a = tf.constant(np.arange(10))

In [4]:
a

<tf.Tensor: id=0, shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [5]:
# 返回a和2中较大的
tf.maximum(a, 2)

<tf.Tensor: id=2, shape=(10,), dtype=int64, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8, 9])>

In [6]:
# 返回a和7中较小的
tf.minimum(a, 7)

<tf.Tensor: id=4, shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 7, 7])>

In [7]:
# 将a限制在2-7之间
tf.clip_by_value(a, 2, 7)

<tf.Tensor: id=8, shape=(10,), dtype=int64, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7, 7])>

In [12]:
m = tf.maximum(a-5, 0, name='max_0_x')

In [13]:
r = tf.nn.relu(a-5, name='relu')

In [14]:
m, r

(<tf.Tensor: id=26, shape=(10,), dtype=int64, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])>,
 <tf.Tensor: id=29, shape=(10,), dtype=int64, numpy=array([0, 0, 0, 0, 0, 0, 1, 2, 3, 4])>)

# 数据限幅clip_by_norm操作

In [15]:
c = tf.random.normal([2, 2], mean=10, stddev=2, seed=123)

In [16]:
c

<tf.Tensor: id=35, shape=(2, 2), dtype=float32, numpy=
array([[14.887075 , 11.306596 ],
       [ 5.8247356,  8.706921 ]], dtype=float32)>

In [17]:
c_norm = tf.norm(c)

In [18]:
c_clip_by_normed = tf.clip_by_norm(c, 12)

In [19]:
print(c_norm, tf.norm(c_clip_by_normed))

tf.Tensor(21.429, shape=(), dtype=float32) tf.Tensor(12.0, shape=(), dtype=float32)


In [20]:
c_norm, tf.norm(c_clip_by_normed)

(<tf.Tensor: id=40, shape=(), dtype=float32, numpy=21.429>,
 <tf.Tensor: id=66, shape=(), dtype=float32, numpy=12.0>)

In [21]:
c_clip_by_normed

<tf.Tensor: id=56, shape=(2, 2), dtype=float32, numpy=
array([[8.336595 , 6.331567 ],
       [3.2617867, 4.8757777]], dtype=float32)>

In [22]:
s = tf.clip_by_norm(c, 12, axes=1)

In [23]:
s

<tf.Tensor: id=82, shape=(2, 2), dtype=float32, numpy=
array([[9.556291 , 7.2579145],
       [5.8247356, 8.706921 ]], dtype=float32)>

In [24]:
s1 = tf.clip_by_norm(c, 12, axes=0)

In [25]:
s1

<tf.Tensor: id=98, shape=(2, 2), dtype=float32, numpy=
array([[11.1750765,  9.50761  ],
       [ 4.3723745,  7.3215675]], dtype=float32)>

In [28]:
tf.norm(s1, axis=0)

<tf.Tensor: id=113, shape=(2,), dtype=float32, numpy=array([11.999999, 12.      ], dtype=float32)>

In [30]:
tf.norm(s,axis=1)

<tf.Tensor: id=118, shape=(2,), dtype=float32, numpy=array([12.000001, 10.475591], dtype=float32)>