In [ ]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
p = tf.random.normal([4,28,28,3])

In [4]:
p.ndim

4

In [5]:
p.shape

TensorShape([4, 28, 28, 3])

In [6]:
p.shape, p.ndim

(TensorShape([4, 28, 28, 3]), 4)

In [7]:
p.dtype

tf.float32

In [8]:
tf.reshape(p, [4,784,3]).shape

TensorShape([4, 784, 3])

# reshape操作

In [9]:
tf.reshape(p, [4,-1,3]).shape

TensorShape([4, 784, 3])

In [10]:
tf.reshape(p, [4,-1]).shape

TensorShape([4, 2352])

# transpose操作

In [11]:
tf.transpose(p).shape

TensorShape([3, 28, 28, 4])

In [12]:
p.shape

TensorShape([4, 28, 28, 3])

In [13]:
tf.transpose(p, perm=[3,1,2,0]).shape

TensorShape([3, 28, 28, 4])

In [14]:
a = tf.zeros([1,2,1,3])

In [17]:
a.shape

TensorShape([1, 2, 1, 3])

# squeeze操作

In [16]:
tf.squeeze(a).shape

TensorShape([2, 3])

In [18]:
tf.squeeze(a, axis=2).shape

TensorShape([1, 2, 3])

# expand_dims操作

In [19]:
s = tf.random.normal([4,35,8])

In [20]:
s.shape, tf.expand_dims(s, axis=0).shape

(TensorShape([4, 35, 8]), TensorShape([1, 4, 35, 8]))

# Broadcasting操作

In [21]:
b = tf.random.normal([4,16,16,32])

In [22]:
b.shape

TensorShape([4, 16, 16, 32])

In [23]:
tf.random.normal([32]).shape

TensorShape([32])

In [24]:
c = b + tf.random.normal([32])  # 不用显式调用

In [25]:
b.shape, c.shape

(TensorShape([4, 16, 16, 32]), TensorShape([4, 16, 16, 32]))

# 数学运算

In [26]:
x = tf.fill([2,2], 6)

In [27]:
x

<tf.Tensor: id=50, shape=(2, 2), dtype=int32, numpy=
array([[6, 6],
       [6, 6]], dtype=int32)>

In [28]:
y = tf.fill([2,2], 7)

In [29]:
y

<tf.Tensor: id=53, shape=(2, 2), dtype=int32, numpy=
array([[7, 7],
       [7, 7]], dtype=int32)>

In [48]:
(x + y).numpy() # 加

array([[13, 13],
       [13, 13]], dtype=int32)

In [31]:
x - y # 减

<tf.Tensor: id=55, shape=(2, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1]], dtype=int32)>

In [32]:
x * y # 乘

<tf.Tensor: id=56, shape=(2, 2), dtype=int32, numpy=
array([[42, 42],
       [42, 42]], dtype=int32)>

In [33]:
x / y # 除

<tf.Tensor: id=59, shape=(2, 2), dtype=float64, numpy=
array([[0.85714286, 0.85714286],
       [0.85714286, 0.85714286]])>

In [34]:
x // y  # 整除  求商

<tf.Tensor: id=60, shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [35]:
y // x

<tf.Tensor: id=61, shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [36]:
x % y # 取余

<tf.Tensor: id=62, shape=(2, 2), dtype=int32, numpy=
array([[6, 6],
       [6, 6]], dtype=int32)>

In [37]:
y % x

<tf.Tensor: id=63, shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [38]:
tf.pow(x, 3) # 幂方

<tf.Tensor: id=65, shape=(2, 2), dtype=int32, numpy=
array([[216, 216],
       [216, 216]], dtype=int32)>

In [39]:
x ** 3 # 幂方

<tf.Tensor: id=67, shape=(2, 2), dtype=int32, numpy=
array([[216, 216],
       [216, 216]], dtype=int32)>

In [40]:
tf.sqrt(tf.cast(x, dtype=tf.float32)) # 开方  浮点型

<tf.Tensor: id=69, shape=(2, 2), dtype=float32, numpy=
array([[2.4494898, 2.4494898],
       [2.4494898, 2.4494898]], dtype=float32)>

In [41]:
e = tf.ones([2,2], dtype=tf.float32)

In [42]:
e

<tf.Tensor: id=72, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [43]:
tf.math.log(e)  # 对数

<tf.Tensor: id=73, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [44]:
tf.math.log(8.) / tf.math.log(2.)  # 以2为底8的对数

<tf.Tensor: id=78, shape=(), dtype=float32, numpy=3.0>

In [45]:
tf.exp(e)

<tf.Tensor: id=79, shape=(2, 2), dtype=float32, numpy=
array([[2.7182817, 2.7182817],
       [2.7182817, 2.7182817]], dtype=float32)>

In [46]:
x @ y # 矩阵相乘

<tf.Tensor: id=80, shape=(2, 2), dtype=int32, numpy=
array([[84, 84],
       [84, 84]], dtype=int32)>

In [47]:
tf.matmul(x, y)  # 矩阵相乘

<tf.Tensor: id=81, shape=(2, 2), dtype=int32, numpy=
array([[84, 84],
       [84, 84]], dtype=int32)>

# Tensor合并与分割

In [49]:
a = tf.ones([4,32,8])

In [50]:
b = tf.ones([4,3,8])

In [53]:
a.shape, b.shape, tf.concat([a,b], axis=1).shape # 合并

(TensorShape([4, 32, 8]), TensorShape([4, 3, 8]), TensorShape([4, 35, 8]))

In [52]:
tf.concat([a,b], axis=0).shape  # 拼接的那个维度可以不相等，其他维度的size以定要相等

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [4,32,8] vs. shape[1] = [4,3,8] [Op:ConcatV2] name: concat

In [54]:
s1 = tf.random.normal([4,35,8])

In [55]:
s2 = tf.random.normal([4,35,8])

In [56]:
tf.concat([s1,s2], axis=0).shape

TensorShape([8, 35, 8])

In [58]:
s1.shape, s2.shape, tf.stack([s1,s2],axis=0).shape # 所有的维度都要相等

(TensorShape([4, 35, 8]), TensorShape([4, 35, 8]), TensorShape([2, 4, 35, 8]))

concat: 拼接的那个维度可以不相等，其他维度的size一定要想等
stack: 所有的维度size都要相等

In [59]:
s = tf.stack([s1,s2], axis=0)

In [60]:
s.shape

TensorShape([2, 4, 35, 8])

In [61]:
q,t =tf.unstack(s, axis=0)  # 分割

In [62]:
q.shape, t.shape

(TensorShape([4, 35, 8]), TensorShape([4, 35, 8]))

In [63]:
res = tf.unstack(s, axis=3)

In [64]:
res[0].shape, res[7].shape # 该轴上的size是多少，就会分割成多少个Tensor

(TensorShape([2, 4, 35]), TensorShape([2, 4, 35]))

In [70]:
tf.unstack(s, num=4,axis=1)

[<tf.Tensor: id=129, shape=(2, 35, 8), dtype=float32, numpy=
 array([[[ 8.17924589e-02,  5.87956309e-01,  2.43609816e-01,
           1.63750064e+00, -2.51478523e-01, -4.81784821e-01,
           4.66709852e-01, -3.76912087e-01],
         [-8.50868225e-02, -1.43982005e+00, -1.35632634e+00,
           5.70373654e-01, -1.17467415e+00,  9.34491515e-01,
           1.32718563e-01, -3.27396661e-01],
         [-8.37831974e-01, -7.98908353e-01,  6.16598688e-02,
          -4.54147935e-01, -1.66327059e+00,  2.79133528e-01,
           1.28436708e+00,  3.86631042e-01],
         [ 2.03361177e+00,  1.79449111e-01, -1.28538504e-01,
          -9.34123397e-01,  2.95777261e-01,  1.22252834e+00,
           3.44604105e-01,  9.44644451e-01],
         [-2.17589170e-01, -4.67520118e-01, -2.46694740e-02,
          -6.69768214e-01, -3.59951556e-02,  1.28621226e-02,
           3.59900802e-01,  2.60804629e+00],
         [-3.90991002e-01, -9.27353371e-03,  4.44832742e-01,
          -1.08851743e+00, -9.97906208e-01,

In [71]:
res = tf.split(s, axis=3, num_or_size_splits=2) # split分割

In [72]:
len(res)

2

In [73]:
res[0].shape, res[1].shape

(TensorShape([2, 4, 35, 4]), TensorShape([2, 4, 35, 4]))

In [74]:
res = tf.split(s, axis=3, num_or_size_splits=[2,3,3])  # split可以指定分割的数量大小

In [75]:
len(res)

3

In [76]:
res[0].shape, res[1].shape, res[2].shape

(TensorShape([2, 4, 35, 2]),
 TensorShape([2, 4, 35, 3]),
 TensorShape([2, 4, 35, 3]))

# 数据统计

L2范数

In [3]:
d = tf.ones([2,2])

In [2]:
import tensorflow as tf

In [4]:
tf.norm(d) # d的L2范数

<tf.Tensor: id=7, shape=(), dtype=float32, numpy=2.0>

In [5]:
tf.sqrt(tf.reduce_sum(tf.square(d)))

<tf.Tensor: id=11, shape=(), dtype=float32, numpy=2.0>

L1范数

In [6]:
tf.norm(d,ord=2, axis=1) # 1轴上的L2范数

<tf.Tensor: id=16, shape=(2,), dtype=float32, numpy=array([1.4142135, 1.4142135], dtype=float32)>

In [7]:
tf.norm(d, ord=1) # d的L1范数

<tf.Tensor: id=20, shape=(), dtype=float32, numpy=4.0>

In [8]:
tf.norm(d, ord=1, axis=0) # 0轴上的L1范数|

<tf.Tensor: id=24, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

reduce_min/max/mean

In [11]:
tf.norm(d, ord=1, axis=1)

<tf.Tensor: id=28, shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [12]:
n = tf.random.normal([4,10])

In [13]:
tf.reduce_max(n) # 最大值

<tf.Tensor: id=36, shape=(), dtype=float32, numpy=1.9441375>

In [14]:
tf.reduce_min(n) # 最小值

<tf.Tensor: id=38, shape=(), dtype=float32, numpy=-1.5346514>

In [15]:
tf.reduce_mean(n)

<tf.Tensor: id=40, shape=(), dtype=float32, numpy=-0.19149314>

In [16]:
tf.reduce_min(n, axis=1)

<tf.Tensor: id=42, shape=(4,), dtype=float32, numpy=array([-1.4904352 , -1.337467  , -1.5346514 , -0.80772364], dtype=float32)>

argmax/argmin

In [17]:
m = tf.constant([5,2,6,9])

In [18]:
tf.argmax(m)

<tf.Tensor: id=45, shape=(), dtype=int64, numpy=3>

In [19]:
tf.argmin(m)

<tf.Tensor: id=47, shape=(), dtype=int64, numpy=1>

In [20]:
g = tf.constant([[1,3,5,2], [2,4,6,1]])

In [21]:
g

<tf.Tensor: id=48, shape=(2, 4), dtype=int32, numpy=
array([[1, 3, 5, 2],
       [2, 4, 6, 1]], dtype=int32)>

In [22]:
tf.argmax(g, axis=0)

<tf.Tensor: id=50, shape=(4,), dtype=int64, numpy=array([1, 1, 1, 0])>

In [23]:
tf.argmin(g, axis=1)

<tf.Tensor: id=52, shape=(2,), dtype=int64, numpy=array([0, 3])>

tf.equal

In [24]:
l1 = tf.constant([1,2,3,2,5])

In [25]:
l2 = range(5)

In [26]:
tf.equal(l1,l2)

<tf.Tensor: id=55, shape=(5,), dtype=bool, numpy=array([False, False, False, False, False])>

In [27]:
l2

range(0, 5)

tf.unique

In [28]:
tf.unique([5,5,1,3,6,1])

Unique(y=<tf.Tensor: id=57, shape=(4,), dtype=int32, numpy=array([5, 1, 3, 6], dtype=int32)>, idx=<tf.Tensor: id=58, shape=(6,), dtype=int32, numpy=array([0, 0, 1, 2, 3, 1], dtype=int32)>)

In [29]:
tf.unique(tf.constant([5,5,1,3,6,1]))

Unique(y=<tf.Tensor: id=60, shape=(4,), dtype=int32, numpy=array([5, 1, 3, 6], dtype=int32)>, idx=<tf.Tensor: id=61, shape=(6,), dtype=int32, numpy=array([0, 0, 1, 2, 3, 1], dtype=int32)>)