In [1]:
import tensorflow as tf

In [2]:
w = tf.Variable(tf.constant(5, dtype=tf.float32))
epoch = 40
learning_rate = 0.2

In [3]:
for epoch in range(epoch):
    with tf.GradientTape() as tape:
        loss = tf.square(w + 1)
    grads = tape.gradient(loss, w)
    w.assign_sub(learning_rate * grads)
    print(f'After {epoch}, loss is {loss}, w is {w.numpy()}')

After 0, loss is 36.0, w is 2.5999999046325684
After 1, loss is 12.959999084472656, w is 1.159999966621399
After 2, loss is 4.665599346160889, w is 0.29600000381469727
After 3, loss is 1.6796159744262695, w is -0.2224000096321106
After 4, loss is 0.604661762714386, w is -0.5334399938583374
After 5, loss is 0.2176782339811325, w is -0.7200639843940735
After 6, loss is 0.07836417108774185, w is -0.832038402557373
After 7, loss is 0.028211098164319992, w is -0.8992230296134949
After 8, loss is 0.010155998170375824, w is -0.9395338296890259
After 9, loss is 0.00365615775808692, w is -0.9637203216552734
After 10, loss is 0.0013162150280550122, w is -0.978232204914093
After 11, loss is 0.00047383690252900124, w is -0.9869393110275269
After 12, loss is 0.00017058159573934972, w is -0.9921635985374451
After 13, loss is 6.140919140307233e-05, w is -0.9952981472015381
After 14, loss is 2.2107420591055416e-05, w is -0.9971789121627808
After 15, loss is 7.958537025842816e-06, w is -0.9983073472976

In [5]:
LR_DECAY = 0.99
LR_STEP = 1

In [7]:
for epoch in range(epoch):
    lr = learning_rate * LR_DECAY ** (epoch / LR_STEP)
    with tf.GradientTape() as tape:
        loss = tf.square(w + 1)
    grads = tape.gradient(loss, w)
    w.assign_sub(lr * grads)
    print(f'After {epoch}, loss is {loss}, w is {w.numpy()}, learning rate is {lr}')

In [8]:
tf.fill([2,2], 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]], dtype=int32)>

In [9]:
tf.ones(4)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>

In [10]:
tf.random.normal([2,2], mean=0, stddev=0.5, seed=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.4056591 ,  0.7422994 ],
       [ 0.03266469, -1.2213521 ]], dtype=float32)>

In [11]:
tf.random.truncated_normal([2,2], mean=0, stddev=0.5, seed=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.4056591 ,  0.7422994 ],
       [ 0.03266469,  0.0496242 ]], dtype=float32)>

In [12]:
x1 = tf.constant([1., 2., 3.], dtype=tf.float64)
print("x1:", x1)
x2 = tf.cast(x1, tf.int32)
print("x2", x2)
print("minimum of x2：", tf.reduce_min(x2))
print("maxmum of x2:", tf.reduce_max(x2))

x1: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
x2 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
minimum of x2： tf.Tensor(1, shape=(), dtype=int32)
maxmum of x2: tf.Tensor(3, shape=(), dtype=int32)


In [13]:
x = tf.constant([[1, 2, 3], [2, 2, 3]])
print("x:", x)
print("mean of x:", tf.reduce_mean(x))  # 求x中所有数的均值
print("sum of x:", tf.reduce_sum(x, axis=1))  # 求每一行的和

x: tf.Tensor(
[[1 2 3]
 [2 2 3]], shape=(2, 3), dtype=int32)
mean of x: tf.Tensor(2, shape=(), dtype=int32)
sum of x: tf.Tensor([6 7], shape=(2,), dtype=int32)


In [14]:
a = tf.ones([1, 3])
b = tf.fill([1, 3], 3.)
print("a:", a)
print("b:", b)
print("a+b:", tf.add(a, b))
print("a-b:", tf.subtract(a, b))
print("a*b:", tf.multiply(a, b))
print("b/a:", tf.divide(b, a))

a: tf.Tensor([[1. 1. 1.]], shape=(1, 3), dtype=float32)
b: tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
a+b: tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float32)
a-b: tf.Tensor([[-2. -2. -2.]], shape=(1, 3), dtype=float32)
a*b: tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)
b/a: tf.Tensor([[3. 3. 3.]], shape=(1, 3), dtype=float32)


In [15]:
a = tf.ones([3, 2])
b = tf.fill([2, 3], 3.)
print("a:", a)
print("b:", b)
print("a*b:", tf.matmul(a, b))

a: tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
b: tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)
a*b: tf.Tensor(
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]], shape=(3, 3), dtype=float32)


In [16]:
feature = tf.constant([12,23,10,17])
label = tf.constant([0,1,1,0])
ds = tf.data.Dataset.from_tensor_slices((feature, label))
ds

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>

In [17]:
for item in ds:
    print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=23>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=17>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [18]:
with tf.GradientTape() as tape:
    x = tf.Variable(tf.constant(3.0))
    y = tf.pow(x, 3)
grad = tape.gradient(y, x)
print(grad)

tf.Tensor(27.0, shape=(), dtype=float32)


In [19]:
seq = ['one', 'two', 'three']
for i, element in enumerate(seq):
    print(i, element)

0 one
1 two
2 three


In [20]:
classes = 3
labels = tf.constant([1,0,2])
output = tf.one_hot(labels, depth=classes)
print('result: ', output)


result:  tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [21]:
x1 = tf.constant([[5.8, 4.0, 1.2, 0.2]])  # 5.8,4.0,1.2,0.2（0）
w1 = tf.constant([[-0.8, -0.34, -1.4],
                  [0.6, 1.3, 0.25],
                  [0.5, 1.45, 0.9],
                  [0.65, 0.7, -1.2]])
b1 = tf.constant([2.52, -3.1, 5.62])
y = tf.matmul(x1, w1) + b1
print("x1.shape:", x1.shape)
print("w1.shape:", w1.shape)
print("b1.shape:", b1.shape)
print("y.shape:", y.shape)
print("y:", y)

x1.shape: (1, 4)
w1.shape: (4, 3)
b1.shape: (3,)
y.shape: (1, 3)
y: tf.Tensor([[ 1.0099998  2.008     -0.6600003]], shape=(1, 3), dtype=float32)


In [22]:
y_dim = tf.squeeze(y)  # 去掉y中纬度1（观察y_dim与 y 效果对比）
y_pro = tf.nn.softmax(y_dim)  # 使y_dim符合概率分布，输出为概率值了
print("y_dim:", y_dim)
print("y_pro:", y_pro)

y_dim: tf.Tensor([ 1.0099998  2.008     -0.6600003], shape=(3,), dtype=float32)
y_pro: tf.Tensor([0.2563381  0.69540703 0.04825489], shape=(3,), dtype=float32)


In [23]:
y = tf.constant([1.01, 2.01, -0.66])
y_pro = tf.nn.softmax(y)

print("After softmax, y_pro is:", y_pro)  # y_pro 符合概率分布

print("The sum of y_pro:", tf.reduce_sum(y_pro))  # 通过softmax后，所有概率加起来和为1

After softmax, y_pro is: tf.Tensor([0.25598174 0.69583046 0.04818781], shape=(3,), dtype=float32)
The sum of y_pro: tf.Tensor(1.0, shape=(), dtype=float32)


In [24]:
import numpy as np
test = np.array([[1, 2, 3], [2, 3, 4], [5, 4, 3], [8, 7, 2]])
print("test:\n", test)
print("每一列的最大值的索引：", tf.argmax(test, axis=0))  # 返回每一列最大值的索引
print("每一行的最大值的索引", tf.argmax(test, axis=1))  # 返回每一行最大值的索引

test:
 [[1 2 3]
 [2 3 4]
 [5 4 3]
 [8 7 2]]
每一列的最大值的索引： tf.Tensor([3 3 1], shape=(3,), dtype=int64)
每一行的最大值的索引 tf.Tensor([2 2 0 0], shape=(4,), dtype=int64)


In [25]:
a = tf.constant([1, 2, 3, 1, 1])
b = tf.constant([0, 1, 3, 4, 5])
c = tf.where(tf.greater(a, b), a, b)  # 若a>b，返回a对应位置的元素，否则返回b对应位置的元素
print("c：", c)

c： tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [26]:
rdm = np.random.RandomState(seed=1)
a = rdm.rand()
b = rdm.rand(2, 3)
print("a:", a)
print("b:", b)

a: 0.417022004702574
b: [[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print("c:\n", c)

c:
 [[1 2 3]
 [4 5 6]]


In [28]:
print(np.hstack((a, b)))

[1 2 3 4 5 6]


In [29]:
rdm = np.random.RandomState(seed=1)
a = rdm.rand()
b = rdm.rand(2, 3)
print("a:", a)
print("b:", b)

a: 0.417022004702574
b: [[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [30]:
# 生成等间隔数值点
x, y = np.mgrid[1:3:1, 2:4:0.5]
# 将x, y拉直，并合并配对为二维张量，生成二维坐标点
grid = np.c_[x.ravel(), y.ravel()]
print("x:\n", x)
print("y:\n", y)
print("x.ravel():\n", x.ravel())
print("y.ravel():\n", y.ravel())
print('grid:\n', grid)

x:
 [[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
y:
 [[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]
x.ravel():
 [1. 1. 1. 1. 2. 2. 2. 2.]
y.ravel():
 [2.  2.5 3.  3.5 2.  2.5 3.  3.5]
grid:
 [[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]


In [33]:
np.mgrid[2:8:1, 1:5:2, 3:6:1]

array([[[[2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3]],

        [[4, 4, 4],
         [4, 4, 4]],

        [[5, 5, 5],
         [5, 5, 5]],

        [[6, 6, 6],
         [6, 6, 6]],

        [[7, 7, 7],
         [7, 7, 7]]],


       [[[1, 1, 1],
         [3, 3, 3]],

        [[1, 1, 1],
         [3, 3, 3]],

        [[1, 1, 1],
         [3, 3, 3]],

        [[1, 1, 1],
         [3, 3, 3]],

        [[1, 1, 1],
         [3, 3, 3]],

        [[1, 1, 1],
         [3, 3, 3]]],


       [[[3, 4, 5],
         [3, 4, 5]],

        [[3, 4, 5],
         [3, 4, 5]],

        [[3, 4, 5],
         [3, 4, 5]],

        [[3, 4, 5],
         [3, 4, 5]],

        [[3, 4, 5],
         [3, 4, 5]],

        [[3, 4, 5],
         [3, 4, 5]]]])

In [34]:
SEED = 23455

rdm = np.random.RandomState(seed=SEED)  # 生成[0,1)之间的随机数
x = rdm.rand(32, 2)
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1, x2) in x]  # 生成噪声[0,1)/10=[0,0.1); [0,0.1)-0.05=[-0.05,0.05)
x = tf.cast(x, dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([2, 1], stddev=1, seed=1))

epoch = 15000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        # 前向传播
        y = tf.matmul(x, w1)
        # 定义损失函数MSE
        loss_mse = tf.reduce_mean(tf.square(y_ - y))
    # 求损失函数对权重的梯度
    grads = tape.gradient(loss_mse, w1)
    # 更新权重
    w1.assign_sub(lr * grads)

    if epoch % 500 == 0:
        print("After %d training steps,w1 is " % (epoch))
        print(w1.numpy(), "\n")
print("Final w1 is: ", w1.numpy())

After 0 training steps,w1 is 
[[-0.20658986]
 [ 0.00788221]] 

After 500 training steps,w1 is 
[[0.50298166]
 [0.7459474 ]] 

After 1000 training steps,w1 is 
[[0.75841296]
 [0.979108  ]] 

After 1500 training steps,w1 is 
[[0.8581708]
 [1.0452577]] 

After 2000 training steps,w1 is 
[[0.9031108]
 [1.0574757]] 

After 2500 training steps,w1 is 
[[0.92757535]
 [1.0533679 ]] 

After 3000 training steps,w1 is 
[[0.9434762]
 [1.0452478]] 

After 3500 training steps,w1 is 
[[0.95511955]
 [1.0369942 ]] 

After 4000 training steps,w1 is 
[[0.96419907]
 [1.0296872 ]] 

After 4500 training steps,w1 is 
[[0.9714882]
 [1.023513 ]] 

After 5000 training steps,w1 is 
[[0.9774142]
 [1.0183884]] 

After 5500 training steps,w1 is 
[[0.98225707]
 [1.0141642 ]] 

After 6000 training steps,w1 is 
[[0.98622364]
 [1.0106924 ]] 

After 6500 training steps,w1 is 
[[0.9894752]
 [1.0078425]] 

After 7000 training steps,w1 is 
[[0.9921414]
 [1.0055034]] 

After 7500 training steps,w1 is 
[[0.99432844]
 [1.00358

In [35]:
SEED = 23455
COST = 1
PROFIT = 99

rdm = np.random.RandomState(SEED)
x = rdm.rand(32, 2)
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1, x2) in x]  # 生成噪声[0,1)/10=[0,0.1); [0,0.1)-0.05=[-0.05,0.05)
x = tf.cast(x, dtype=tf.float32)

w1 = tf.Variable(tf.random.normal([2, 1], stddev=1, seed=1))

epoch = 10000
lr = 0.002

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y = tf.matmul(x, w1)
        # 自定义损失函数
        loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y - y_) * COST, (y_ - y) * PROFIT))

    grads = tape.gradient(loss, w1)
    w1.assign_sub(lr * grads)

    if epoch % 500 == 0:
        print("After %d training steps,w1 is " % (epoch))
        print(w1.numpy(), "\n")
print("Final w1 is: ", w1.numpy())

After 0 training steps,w1 is 
[[2.3406312]
 [3.5071864]] 

After 500 training steps,w1 is 
[[1.1319451]
 [1.1269131]] 

After 1000 training steps,w1 is 
[[1.1809582]
 [1.1694897]] 

After 1500 training steps,w1 is 
[[1.1505198]
 [1.0243032]] 

After 2000 training steps,w1 is 
[[1.1408995]
 [1.0555867]] 

After 2500 training steps,w1 is 
[[1.1312798]
 [1.0868708]] 

After 3000 training steps,w1 is 
[[1.1216598]
 [1.1181545]] 

After 3500 training steps,w1 is 
[[1.1706731]
 [1.1607316]] 

After 4000 training steps,w1 is 
[[1.1402348]
 [1.015545 ]] 

After 4500 training steps,w1 is 
[[1.1306151]
 [1.0468291]] 

After 5000 training steps,w1 is 
[[1.1209952]
 [1.078113 ]] 

After 5500 training steps,w1 is 
[[1.1113749]
 [1.1093965]] 

After 6000 training steps,w1 is 
[[1.1603881]
 [1.1519734]] 

After 6500 training steps,w1 is 
[[1.1507683]
 [1.1832573]] 

After 7000 training steps,w1 is 
[[1.1203301]
 [1.0380709]] 

After 7500 training steps,w1 is 
[[1.1107103]
 [1.0693549]] 

After 8000 t

In [36]:
# 交叉熵损失
loss_ce1 = tf.losses.categorical_crossentropy([1, 0], [0.6, 0.4])
loss_ce2 = tf.losses.categorical_crossentropy([1, 0], [0.8, 0.2])
print("loss_ce1:", loss_ce1)
print("loss_ce2:", loss_ce2)

loss_ce1: tf.Tensor(0.5108256, shape=(), dtype=float32)
loss_ce2: tf.Tensor(0.22314353, shape=(), dtype=float32)


In [37]:
y_ = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]])
y = np.array([[12, 3, 2], [3, 10, 1], [1, 2, 5], [4, 6.5, 1.2], [3, 6, 1]])
y_pro = tf.nn.softmax(y)
loss_ce1 = tf.losses.categorical_crossentropy(y_,y_pro)
loss_ce2 = tf.nn.softmax_cross_entropy_with_logits(y_, y)

print('分步计算的结果:\n', loss_ce1)
print('结合计算的结果:\n', loss_ce2)

分步计算的结果:
 tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64)
结合计算的结果:
 tf.Tensor(
[1.68795487e-04 1.03475622e-03 6.58839038e-02 2.58349207e+00
 5.49852354e-02], shape=(5,), dtype=float64)
