In [1]:
import tensorflow as tf
import pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.set_printoptions(precision=4)

In [3]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])

In [4]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [5]:
for elem in dataset:
    print(elem)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [6]:
it = iter(dataset)
next(it)

<tf.Tensor: id=19, shape=(), dtype=int32, numpy=8>

In [7]:
next(it).numpy()

3

In [8]:
dataset.reduce(0, lambda state, value: state + value)

<tf.Tensor: id=28, shape=(), dtype=int32, numpy=22>

In [9]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))

In [10]:
dataset1.element_spec

TensorSpec(shape=(10,), dtype=tf.float32, name=None)

In [11]:
dataset1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [12]:
for elem in dataset1:
    print(elem)

tf.Tensor([0.4922 0.2478 0.0062 0.784  0.6469 0.8102 0.3899 0.5188 0.7252 0.2678], shape=(10,), dtype=float32)
tf.Tensor([0.7446 0.9267 0.3502 0.4022 0.8132 0.3101 0.2867 0.7793 0.0561 0.4786], shape=(10,), dtype=float32)
tf.Tensor([0.5649 0.7817 0.4327 0.727  0.7211 0.8074 0.1114 0.8841 0.2291 0.9553], shape=(10,), dtype=float32)
tf.Tensor([0.4235 0.9406 0.1881 0.2266 0.6192 0.447  0.7224 0.3412 0.9839 0.3046], shape=(10,), dtype=float32)


In [13]:
dataset2 = tf.data.Dataset.from_tensor_slices((tf.random.uniform([4]),
                                             tf.random.uniform([4, 10], maxval=100, dtype=tf.int32)))

In [14]:
dataset2

<TensorSliceDataset shapes: ((), (10,)), types: (tf.float32, tf.int32)>

In [15]:
for elem in dataset2:
    print(elem)

(<tf.Tensor: id=63, shape=(), dtype=float32, numpy=0.25675035>, <tf.Tensor: id=64, shape=(10,), dtype=int32, numpy=array([67, 92, 51, 73, 62, 62, 79, 15, 14, 21], dtype=int32)>)
(<tf.Tensor: id=65, shape=(), dtype=float32, numpy=0.05544436>, <tf.Tensor: id=66, shape=(10,), dtype=int32, numpy=array([53, 98, 73, 17, 83,  0, 81, 45, 36, 40], dtype=int32)>)
(<tf.Tensor: id=67, shape=(), dtype=float32, numpy=0.0076898336>, <tf.Tensor: id=68, shape=(10,), dtype=int32, numpy=array([82,  7, 40, 94, 68, 71, 72, 65, 86, 97], dtype=int32)>)
(<tf.Tensor: id=69, shape=(), dtype=float32, numpy=0.09627938>, <tf.Tensor: id=70, shape=(10,), dtype=int32, numpy=array([23, 98, 88, 88, 34, 41,  2, 43, 52,  8], dtype=int32)>)


In [16]:
dataset2.element_spec

(TensorSpec(shape=(), dtype=tf.float32, name=None),
 TensorSpec(shape=(10,), dtype=tf.int32, name=None))

In [17]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

In [18]:
dataset3.element_spec

(TensorSpec(shape=(10,), dtype=tf.float32, name=None),
 (TensorSpec(shape=(), dtype=tf.float32, name=None),
  TensorSpec(shape=(10,), dtype=tf.int32, name=None)))

In [19]:
dataset4 = tf.data.Dataset.from_tensors(tf.SparseTensor(indices=[[0,0],[1,2]], values=[1, 2],
                                                       dense_shape=[3, 4]))

In [20]:
dataset4.element_spec

SparseTensorSpec(TensorShape([3, 4]), tf.int32)

In [21]:
dataset4.element_spec.value_type

tensorflow.python.framework.sparse_tensor.SparseTensor

In [22]:
dataset1 = tf.data.Dataset.from_tensor_slices(
    tf.random.uniform([4, 10], minval=1, maxval=10, dtype=tf.int32))
dataset1

<TensorSliceDataset shapes: (10,), types: tf.int32>

In [23]:
for z in dataset1:
    print(z.numpy())

[6 8 1 4 7 8 9 8 8 3]
[1 3 7 1 7 8 3 3 6 6]
[9 7 7 3 7 7 3 3 5 7]
[9 3 7 7 7 6 2 1 7 9]


In [24]:
dataset2 = tf.data.Dataset.from_tensor_slices(
    (tf.random.uniform([4]),
    tf.random.uniform([4, 100], maxval=100, dtype=tf.int32)))
dataset2

<TensorSliceDataset shapes: ((), (100,)), types: (tf.float32, tf.int32)>

In [25]:
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))
dataset3

<ZipDataset shapes: ((10,), ((), (100,))), types: (tf.int32, (tf.float32, tf.int32))>

In [26]:
for a, (b, c) in dataset3:
    print('shapes: {a.shape}, {b.shape}, {c.shape}'.format(a=a, b=b, c=c))

shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
shapes: (10,), (), (100,)
