In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn
import os
import sys
print(tf.__version__)
print(sys.version_info)
for module in tf, np, pd, sklearn:
    print(module.__name__, module.__version__)

/home/kdd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarnin

2.0.0-beta1
sys.version_info(major=3, minor=6, micro=5, releaselevel='final', serial=0)
tensorflow 2.0.0-beta1
numpy 1.18.1
pandas 0.24.1
sklearn 0.21.2


/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/kdd/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub

# 从numpy数组构建数据集

In [2]:
dataset = tf.data.Dataset.from_tensor_slices(np.arange(10))
print(dataset)

<TensorSliceDataset shapes: (), types: tf.int64>


In [3]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [4]:
# repeat 将数据重复几次，相当于epoch的作用
# batch 每批次获取的样本数量
dataset1 = dataset.repeat(4).batch(5)
for item in dataset1:
    print(item)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int64)


In [5]:
for item in dataset.repeat(3).batch(7):
    print(item)

tf.Tensor([0 1 2 3 4 5 6], shape=(7,), dtype=int64)
tf.Tensor([7 8 9 0 1 2 3], shape=(7,), dtype=int64)
tf.Tensor([4 5 6 7 8 9 0], shape=(7,), dtype=int64)
tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)


In [8]:
# interleave 将dataset中元素进行处理，相当于map的功能
# cycle_length 多少个Tensor一个循环
# block_lenght 一次获取v的多少个元素
dataset2 = dataset1.interleave(
    lambda v: tf.data.Dataset.from_tensor_slices(v), cycle_length=4, block_length=3)
for item in dataset2:
    print(item)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype

# 从元组/字典构建数据集

In [9]:
x = np.array([[1,2,3], [2,3,4], [3,4,5]])
y = np.array(['Beijing', 'Shanghai', 'Chongqing'])
dataset3 = tf.data.Dataset.from_tensor_slices((x,y))
for item in dataset3:
    print(item)

(<tf.Tensor: id=363, shape=(3,), dtype=int64, numpy=array([1, 2, 3])>, <tf.Tensor: id=364, shape=(), dtype=string, numpy=b'Beijing'>)
(<tf.Tensor: id=367, shape=(3,), dtype=int64, numpy=array([2, 3, 4])>, <tf.Tensor: id=368, shape=(), dtype=string, numpy=b'Shanghai'>)
(<tf.Tensor: id=371, shape=(3,), dtype=int64, numpy=array([3, 4, 5])>, <tf.Tensor: id=372, shape=(), dtype=string, numpy=b'Chongqing'>)


In [11]:
for item_x, item_y in dataset3:
    print(item_x.numpy(), item_y.numpy().decode('utf-8'))

[1 2 3] Beijing
[2 3 4] Shanghai
[3 4 5] Chongqing


In [12]:
for item in dataset3:
    print(item[0], item[1])

tf.Tensor([1 2 3], shape=(3,), dtype=int64) tf.Tensor(b'Beijing', shape=(), dtype=string)
tf.Tensor([2 3 4], shape=(3,), dtype=int64) tf.Tensor(b'Shanghai', shape=(), dtype=string)
tf.Tensor([3 4 5], shape=(3,), dtype=int64) tf.Tensor(b'Chongqing', shape=(), dtype=string)


In [13]:
for item in tf.data.Dataset.from_tensor_slices({'coordinate': x, 'city': y}):
    print(item['city'].numpy(), item['coordinate'].numpy())

b'Beijing' [1 2 3]
b'Shanghai' [2 3 4]
b'Chongqing' [3 4 5]


# 生成CSV文件

In [14]:
# 获取california_housing数据集
from sklearn.datasets import fetch_california_housing
house = fetch_california_housing()

In [15]:
from sklearn.model_selection import train_test_split
x_train_all, x_test, y_train_all, y_test = train_test_split(
house.data, house.target,random_state=7)
x_train, x_valid, y_train, y_valid = train_test_split(x_train_all, y_train_all, random_state=11)
print(x_train_all.shape, y_train_all.shape)
print(x_train.shape, y_train.shape)
print(x_valid.shape, y_valid.shape)
print(x_test.shape, y_test.shape)

(15480, 8) (15480,)
(11610, 8) (11610,)
(3870, 8) (3870,)
(5160, 8) (5160,)


In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_valid_scaled = scaler.transform(x_valid)
x_test_scaled = scaler.transform(x_test)

In [21]:
output_dir = "./data/csv/"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)
# 将feature和label拼接起来   
train_data = np.c_[x_train_scaled, y_train]
valid_data = np.c_[x_valid_scaled, y_valid]
test_data = np.c_[x_test_scaled, y_test]
# 获取字段名称
house_cols = house.feature_names + ['MHV']
cols_str = ','.join(house_cols)


In [22]:
# 定义一个保存csv文件的方法
def save_to_csv(output_dir, data, name_prefix, header=None, n_parts=10):
    '''
    output_dir: 保存路径
    data: 要保存的数据
    name_prefix: 保存的文件名前缀
    header: 表头
    n_parts: 保存几部分
    '''
    path_format = os.path.join(output_dir, '{}_{:2d}.csv')
    filenames = []
    for file_idx, row_indices in enumerate(np.array_split(np.arange(len(data)), n_parts)):
        part_csv = path_format.format(name_prefix, file_idx)
        filenames.append(part_csv)
        with open(part_csv, 'wt', encoding='utf-8') as f:
            if header is not None:
                f.write(header+'\n')
            for row_index in row_indices:
                f.write(','.join([repr(col) for col in data[row_index]]))
                f.write('\n')
    return filenames

In [23]:
train_filenames = save_to_csv(output_dir, train_data, 'train', cols_str, n_parts=20)
valid_filenames = save_to_csv(output_dir, valid_data, 'valid', cols_str, n_parts=10)
test_filenames = save_to_csv(output_dir, test_data, 'test', cols_str, n_parts=10)

# 读取CSV文件

In [24]:
import pprint
print('train_filenames:')
pprint.pprint(train_filenames)

train_filenames:
['./data/csv/train_ 0.csv',
 './data/csv/train_ 1.csv',
 './data/csv/train_ 2.csv',
 './data/csv/train_ 3.csv',
 './data/csv/train_ 4.csv',
 './data/csv/train_ 5.csv',
 './data/csv/train_ 6.csv',
 './data/csv/train_ 7.csv',
 './data/csv/train_ 8.csv',
 './data/csv/train_ 9.csv',
 './data/csv/train_10.csv',
 './data/csv/train_11.csv',
 './data/csv/train_12.csv',
 './data/csv/train_13.csv',
 './data/csv/train_14.csv',
 './data/csv/train_15.csv',
 './data/csv/train_16.csv',
 './data/csv/train_17.csv',
 './data/csv/train_18.csv',
 './data/csv/train_19.csv']


In [25]:
print(train_filenames)

['./data/csv/train_ 0.csv', './data/csv/train_ 1.csv', './data/csv/train_ 2.csv', './data/csv/train_ 3.csv', './data/csv/train_ 4.csv', './data/csv/train_ 5.csv', './data/csv/train_ 6.csv', './data/csv/train_ 7.csv', './data/csv/train_ 8.csv', './data/csv/train_ 9.csv', './data/csv/train_10.csv', './data/csv/train_11.csv', './data/csv/train_12.csv', './data/csv/train_13.csv', './data/csv/train_14.csv', './data/csv/train_15.csv', './data/csv/train_16.csv', './data/csv/train_17.csv', './data/csv/train_18.csv', './data/csv/train_19.csv']


In [26]:
# 构建文件名数据集
filenames_dataset = tf.data.Dataset.list_files(train_filenames)
print(filenames_dataset)
for filename in filenames_dataset:
    print(filename)

<DatasetV1Adapter shapes: (), types: tf.string>
tf.Tensor(b'./data/csv/train_ 0.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_ 6.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_16.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_ 9.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_ 3.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_ 8.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_ 2.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_13.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_19.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_ 1.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_12.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_11.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_15.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_18.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv/train_10.csv', shape=(), dtype=string)
tf.Tensor(b'./data/csv

In [28]:
n_readers = 5
dataset = filenames_dataset.interleave(lambda filename: tf.data.TextLineDataset(filename).skip(1),
                                      cycle_length=n_readers)
for line in dataset.take(5): # 取前5行
    print(line.numpy().decode('utf-8'))

0.801544314532886,0.27216142415910205,-0.11624392696666119,-0.2023115137272354,-0.5430515742518128,-0.021039615516440048,-0.5897620622908205,-0.08241845654707416,3.226
-0.32652634129448693,0.43236189741438374,-0.09345459539684739,-0.08402991822890092,0.8460035745154013,-0.0266316482653991,-0.5617679242614233,0.1422875991184281,2.431
-0.6672227549433569,-0.04823952235146133,0.34529405473316743,0.5382668657200925,1.8521839533415545,-0.0611253832474835,-0.8417093045554153,1.520484740533546,1.59
-1.0775077698160966,-0.44874070548966555,-0.5680568205591913,-0.14269262164909954,-0.09666677138213985,0.12326468238687088,-0.3144863716683942,-0.4818958888413162,0.978
0.15782311132800697,0.43236189741438374,0.3379948076652917,-0.015880306122244434,-0.3733890577139493,-0.05305245634489608,0.8006134598360177,-1.2359095422966828,3.169


In [29]:
# 解析csv中的内容， 举个栗子
sample_str = '1,2,3,4,5'
records = [
    tf.constant(0, dtype=tf.int32),
    0,
    np.nan,
    'hell',
    tf.constant([])
]
parsed_fields = tf.io.decode_csv(sample_str, records)
for item in parsed_fields:
    print(item)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(b'4', shape=(), dtype=string)
tf.Tensor(5.0, shape=(), dtype=float32)


In [30]:
tf.io.decode_csv(',,,,', records)

InvalidArgumentError: Field 4 is required but missing in record 0! [Op:DecodeCSV]

In [31]:
try:
    tf.io.decode_csv(',,,,', records)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

Field 4 is required but missing in record 0! [Op:DecodeCSV]


In [32]:
try:
    tf.io.decode_csv('11,2,5', records)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

Expect 5 fields but have 3 in record 0 [Op:DecodeCSV]


In [33]:
# 定义一个解析csv每行内容的方法
def parse_csv_line(line, n_fields):
    records = [tf.constant(np.nan)]*n_fields
    parsed_fields = tf.io.decode_csv(line, records)
    x = tf.stack(parsed_fields[0:-1])
    y = tf.stack(parsed_fields[-1])
    return x, y

In [34]:
parse_csv_line(b'0.6303435674178064,1.874166156711919,-0.06713214279531016,-0.12543366804152128,-0.19737553788322462,-0.022722631725889016,-0.692407235065288,0.7265233438487496,2.419',n_fields=9)

(<tf.Tensor: id=629, shape=(8,), dtype=float32, numpy=
 array([ 0.63034356,  1.8741661 , -0.06713215, -0.12543367, -0.19737554,
        -0.02272263, -0.69240725,  0.72652334], dtype=float32)>,
 <tf.Tensor: id=628, shape=(), dtype=float32, numpy=2.419>)

In [35]:
# 定义一个解析csv每行内容的方法
def parse_csv_line(line, n_fields=9):
    records = [tf.constant(np.nan)]*n_fields
    parsed_fields = tf.io.decode_csv(line, records)
    x = tf.stack(parsed_fields[0:-1])
    y = tf.stack(parsed_fields[-1])
    return x, y

# 定义一个多线程读取csv文件并解析的方法
def csv_read_dataset(filenames, n_readers=5, batch_size=32, n_parse_threads=5, shuffle_buffer_size=10000):
    '''
    filenames: 文件名列表
    n_readers: 并行程度
    batch_size: 批大小
    n_parse_threads: 解析的并行程度
    shuffle_buffer_size: 
    '''
    filenames_dataset = tf.data.Dataset.list_files(filenames)
    filenames_dataset = filenames_dataset.repeat()
    dataset = filenames_dataset.interleave(
        lambda filename: tf.data.TextLineDataset(filename).skip(1),
        cycle_length=n_readers)
    dataset.shuffle(shuffle_buffer_size)
    dataset = dataset.map(parse_csv_line, num_parallel_calls=n_parse_threads)
    dataset = dataset.batch(batch_size)
    return dataset

In [36]:
train_set = csv_read_dataset(train_filenames, batch_size=3)
for x_batch, y_batch in train_set.take(2):
    print('x:')
    pprint.pprint(x_batch)
    print('y:')
    pprint.pprint(y_batch)

x:
<tf.Tensor: id=712, shape=(3, 8), dtype=float32, numpy=
array([[ 0.40127665, -0.92934215, -0.0533305 , -0.18659453,  0.65456617,
         0.02643447,  0.9312528 , -1.4406418 ],
       [ 0.48530516, -0.8492419 , -0.06530126, -0.02337966,  1.4974351 ,
        -0.07790658, -0.90236324,  0.78145146],
       [ 0.63034356,  1.8741661 , -0.06713215, -0.12543367, -0.19737554,
        -0.02272263, -0.69240725,  0.72652334]], dtype=float32)>
y:
<tf.Tensor: id=713, shape=(3,), dtype=float32, numpy=array([2.512, 2.956, 2.419], dtype=float32)>
x:
<tf.Tensor: id=716, shape=(3, 8), dtype=float32, numpy=
array([[ 0.04326301, -1.0895426 , -0.38878718, -0.10789865, -0.68186635,
        -0.0723871 , -0.8883662 ,  0.8213992 ],
       [ 0.81150836, -0.04823952,  0.5187339 , -0.0293864 , -0.03406402,
        -0.05081595, -0.7157357 ,  0.91627514],
       [-0.8757754 ,  1.8741661 , -0.94874996, -0.09657185, -0.7163432 ,
        -0.07790191,  0.98257536, -1.4206679 ]], dtype=float32)>
y:
<tf.Tensor: id=717

In [37]:
train_set = csv_read_dataset(train_filenames, batch_size=32)
valid_set = csv_read_dataset(valid_filenames, batch_size=32)
test_set = csv_read_dataset(test_filenames, batch_size=32)